# Generated by Django 5.0.4 on 2025-01-09 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=2000),
        ),
    ]
