# Generated by Django 5.0.4 on 2025-01-09 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='intertransferx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='088bee4e296d', max_length=50, null=True)),
                ('accname', models.CharField(blank=True, max_length=50, null=True)),
                ('accnum', models.CharField(blank=True, default=3207249625283, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('swiftcode', models.CharField(blank=True, default='TWNFZR72', max_length=50, null=True)),
                ('ibannumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ountry', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=900, null=True)),
                ('appoved', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='localtransferx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='9c907d125', max_length=50, null=True)),
                ('accname', models.CharField(blank=True, max_length=50, null=True)),
                ('accnum', models.CharField(blank=True, default=9421534613609, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('appoved', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='Accountnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='intertransfer',
            field=models.ManyToManyField(blank=True, to='app.intertransferx'),
        ),
        migrations.AddField(
            model_name='account',
            name='localtransfer',
            field=models.ManyToManyField(blank=True, to='app.localtransferx'),
        ),
    ]
