# Generated by Django 5.0.4 on 2025-01-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_account_accountnum_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intertransferx',
            old_name='ibannumber',
            new_name='Bankaddress',
        ),
        migrations.RemoveField(
            model_name='intertransferx',
            name='ountry',
        ),
        migrations.AddField(
            model_name='account',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, default='0000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localtransferx',
            name='Routing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Accountnum',
            field=models.CharField(blank=True, default='76a030d995c', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='accnum',
            field=models.CharField(blank=True, default=8244565102033, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='swiftcode',
            field=models.CharField(blank=True, default='QUZJYCPU7X4', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='97d0c2398c59', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='accnum',
            field=models.CharField(blank=True, default=7718767485903, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='uuid',
            field=models.CharField(blank=True, default='2777fbdb6', max_length=50, null=True),
        ),
    ]
