# Generated by Django 5.0.4 on 2025-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_account_accountnum_alter_intertransferx_accnum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjecttiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='caf46e3abe62', max_length=50, null=True)),
                ('Subject', models.CharField(blank=True, max_length=50, null=True)),
                ('Priority', models.CharField(blank=True, default=7867082600578, max_length=50, null=True)),
                ('Details', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='Accountnum',
            field=models.CharField(blank=True, default='44dfa7c884c', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='accnum',
            field=models.CharField(blank=True, default=9162338526969, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='swiftcode',
            field=models.CharField(blank=True, default='CHNGUPV2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='9f17431a01d7', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='accnum',
            field=models.CharField(blank=True, default=8953623097019, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='uuid',
            field=models.CharField(blank=True, default='936029f2e', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Subjecttiketmain',
            field=models.ManyToManyField(blank=True, to='app.subjecttiket'),
        ),
    ]
