# Generated by Django 5.0.4 on 2025-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_bankname_localtransferx_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Accountnum',
            field=models.CharField(blank=True, default='8a0a49e242b', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='accnum',
            field=models.CharField(blank=True, default=3704348072179, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='swiftcode',
            field=models.CharField(blank=True, default='QVZFLHUT77U', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='a1b14b265699', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='accnum',
            field=models.CharField(blank=True, default=8056918736460, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='uuid',
            field=models.CharField(blank=True, default='2298bd8bf', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttiket',
            name='Priority',
            field=models.CharField(blank=True, default=3970904398064, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttiket',
            name='uuid',
            field=models.CharField(blank=True, default='f7a02350bbbc', max_length=50, null=True),
        ),
    ]
