# Generated by Django 5.0.4 on 2025-01-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_account_accountnum_alter_intertransferx_accnum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intertransferx',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='account',
            name='Accountnum',
            field=models.CharField(blank=True, default='3e61d6a5d67', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='accnum',
            field=models.CharField(blank=True, default=7473567932684, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='swiftcode',
            field=models.CharField(blank=True, default='KBHUIHR9', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intertransferx',
            name='uuid',
            field=models.CharField(blank=True, default='1c7846987eb2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='accnum',
            field=models.CharField(blank=True, default=4774642289151, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localtransferx',
            name='uuid',
            field=models.CharField(blank=True, default='bf00f0655', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttiket',
            name='Priority',
            field=models.CharField(blank=True, default=4180355949888, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttiket',
            name='uuid',
            field=models.CharField(blank=True, default='6a301c9ec56f', max_length=50, null=True),
        ),
    ]
